using System;
using System.Collections.Generic;

namespace CoreWithSqlServerConnection
{
    public partial class TblEmployee
    {
        public int IntEmployeeId { get; set; }
        public string StrEmployeeCode { get; set; }
        public int? IntAppTypeId { get; set; }
        public string StrEmployeeName { get; set; }
        public string StrSortName { get; set; }
        public int? IntGroupId { get; set; }
        public int? IntUnitId { get; set; }
        public int? IntJobStationId { get; set; }
        public int? IntJobTypeId { get; set; }
        public int? IntDesignationId { get; set; }
        public int? IntDepartmentId { get; set; }
        public int? IntDutyCatagoryId { get; set; }
        public int? IntPresentShiftId { get; set; }
        public int? IntDayOffId { get; set; }
        public string StrEmployeePunchCardCode { get; set; }
        public string StrContactPeriod { get; set; }
        public int? IntSuperviserId { get; set; }
        public DateTime? DteJoiningDate { get; set; }
        public DateTime? DteAppointmentDate { get; set; }
        public string StrResponsibility { get; set; }
        public string StrBloodGroup { get; set; }
        public string StrOfficeEmail { get; set; }
        public string StrBankAccountNo { get; set; }
        public decimal? MonSalary { get; set; }
        public string StrNationalId { get; set; }
        public string StrGender { get; set; }
        public int? IntSoftwareLoginUserId { get; set; }
        public bool? YsnActive { get; set; }
        public string StrBankName { get; set; }
        public string StrBranchName { get; set; }
        public TimeSpan? TimeOfficeHour { get; set; }
        public decimal? MonBasic { get; set; }
        public bool? YsnSalaryHold { get; set; }
        public bool? YsnNewCardInstallation { get; set; }
        public string StrSalaryUnit { get; set; }
        public string StrAge { get; set; }
        public string StrPermanentAddress { get; set; }
        public string StrPresentAddress { get; set; }
        public string StrContactNo1 { get; set; }
        public string StrContactNo2 { get; set; }
        public string StrEmpImageUrl { get; set; }
        public string StrEmployeeCodePrevious { get; set; }
        public string StrPaymentType { get; set; }
        public int? IntReligionId { get; set; }
        public string StrEmergencyPhoneNo { get; set; }
        public string StrEmergencyPersonRelation { get; set; }
        public string StrLastDegree { get; set; }
        public string StrSubjectName { get; set; }
        public string StrInstitute { get; set; }
        public string StrLocalGuardianName { get; set; }
        public string StrLocalGuardianAddress { get; set; }
        public string StrLocalGuardianPhoneNo { get; set; }
        public string StrLocalGuardianRelation { get; set; }
        public string StrGovtEmployeeName { get; set; }
        public string StrGovtEmployeeAddress { get; set; }
        public string StrGovtEmployeePhoneNo { get; set; }
        public string StrGovtEmployeeDesignation { get; set; }
        public string StrGovtEmployeeDepartment { get; set; }
        public string StrGovtEmployeeRelation { get; set; }
        public string StrDocumentType { get; set; }
        public string StrDocumentLink1 { get; set; }
        public string StrDocumentLink2 { get; set; }
        public string StrDocumentLink3 { get; set; }
        public string StrDocumentLink4 { get; set; }
        public string StrDocumentLink5 { get; set; }
        public string StrDocumentLink6 { get; set; }
        public string StrDocumentLink7 { get; set; }
        public string StrDocumentLink8 { get; set; }
        public string StrDocumentLink9 { get; set; }
        public string StrTinno { get; set; }
        public int? IntDepot { get; set; }
        public int? IntBankId { get; set; }
        public int? IntDistrictId { get; set; }
        public int? IntBranchId { get; set; }
        public string StrFirstName { get; set; }
        public string StrMiddleName { get; set; }
        public string StrLastName { get; set; }
        public string StrAlias { get; set; }
        public string StrOrganisationUnit { get; set; }
        public string StrManager { get; set; }
        public string StrCountry { get; set; }
        public string StrCity { get; set; }
        public string StrMailBox { get; set; }
        public string StrPassword { get; set; }
        public string StrIpphone { get; set; }
        public int? IntWorkCenterId { get; set; }
        public string StrArchiveMailbox { get; set; }
        public DateTime? DteBirth { get; set; }
        public string StrGlcode { get; set; }
        public DateTime? DteConfirmation { get; set; }
        public DateTime? DteResign { get; set; }
        public string StrMobileImeno { get; set; }
        public int? IntUseVheicleId { get; set; }
        public decimal? MonPersonalMilageRate { get; set; }
        public int? IntPersonalUseFuelRateType { get; set; }
        public string StrFloorAccess { get; set; }
    }
}
